# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
bootTimeInference <- function(ret, b, M, Delta_null = 0.0, digits = 4L) {
    .Call('bootTimeInference_bootTimeInference', PACKAGE = 'bootTimeInference', ret, b, M, Delta_null, digits)
}

#' @export
blockSizeCalibrate <- function(ret, b_vec = as.integer( c(1, 3, 6, 10)), alpha = 0.05, M = 199L, K = 1000L, b_av = 5L, T_start = 50L) {
    .Call('bootTimeInference_blockSizeCalibrate', PACKAGE = 'bootTimeInference', ret, b_vec, alpha, M, K, b_av, T_start)
}

